### ISSUE TITLE
History of sent data

### ISSUE THREAD

**Issue by diggit** [ivanovp/iserterm#1]
When I already sent character `d`, I cant send `D`, because it gets corrected to lowercase `d`. History should be available on request(arrow up etc.). Suggestions, the way are provided now, can produce unwanted results.

I have `1234567` in history, now when I write `123`, input field is prefilled with `1234567` and I have to press backspace to remove excessive characters.

**Comment by ivanovp** [comment]
History is case sensitive now.

**Comment by diggit** [comment]
Thanks!

I would be great if history could be less intrusive and show suggestions in drop-down list instead of pre-filling field.

**Comment by ivanovp** [comment]
Auto completion can be configured in console settings. Case sensitivity and pop-up list can be selected as well.

**Comment by diggit** [comment]
Awesome!

One last "problem" I noticed is the STOP button. The only difference between active and inactive is is button state itself. It is hard to recognize state of it in my dark GUI theme. It would be great to have RED icon for disabled output and GREEN icon for enabled output. What do you think?

**Comment by ivanovp** [comment]
True, it is not clearly visible when it is stopped. I'll open another issue.
