### ISSUE TITLE
Timestamp on every line

### ISSUE THREAD

**Issue by ivanovp** [ivanovp/iserterm#3]
Add timestamp after every new line character.
Note: needs a lot of re-design.

**Comment by diggit** [comment]
This is great idea. AFAIK there is no serial terminal capable of it.

It should be possible to hide them on the fly to copy contents with or without timestamps. Like hexadecimal view switching.
Toggling between absolute and relative timestamps could be useful too.

**Comment by ivanovp** [comment]
Comment to myself: use two buffers. One with timestamp, one without timestamp. The latter one can be used for hexadecimal view.

**Comment by ivanovp** [comment]
Implemented. Two buffers are used in Console class: one contains timestamp, one is without timestamp.
